### ISSUE TITLE
Képes ikonok próba

### ISSUE THREAD

**Issue by Sogi15** [Playmaker1210/Playmaker1210.github.io#2]
[teszt.zip](https://github.com/Playmaker1210/Playmaker1210.github.io/files/7925587/teszt.zip)

Elvileg ez így rajta lesz a szöveg a képen a háttérképet cserélhetjük stb illetve az ikonoktól függ majd mekkora legyen a padding stb.

**Comment by Playmaker1210** [comment]
jo lesz most neztem meg gepen majd hozza adjuk
