### ISSUE TITLE
Elcsúszott a topic cucc

### ISSUE THREAD

**Issue by Sogi15** [Playmaker1210/Playmaker1210.github.io#4]
Nálam a böngészőben elvileg helyesen volt a bootstrap, de most felnéztem az oldalra és ott mobil módban el van csúszva (nagyobb mint kellene). Néztem a telómon ott is el van meg egy Galaxy A51-en is ugyan úgy el van csúszva majd a kódra rá kell nézni mit kavart be a bootstrap.

**Comment by Playmaker1210** [comment]
javitva
